"""Public contracts for the Photon-QDrivers photonic control plane."""

from .acquisition import AcquisitionKind, AcquisitionRecord
from .board import (
    BOARD_CAPABILITIES_PROTOCOL,
    BOARD_PROGRAM_PROTOCOL,
    BOARD_REGISTER_MAP,
    BOARD_RESULT_PROTOCOL,
    BoardCapabilities,
    BoardExecutionResult,
    BoardProgramImage,
    P6BoardBridge,
    SoftwareBoard,
    decode_control_request_frame,
    encode_control_request_frame,
    encode_control_result_frame,
)
from .loopback import (
    ANALYTIC_LOOPBACK_MODEL_ID,
    ANALYTIC_LOOPBACK_SCHEMA_VERSION,
    AnalyticLoopbackConfig,
    AnalyticLoopbackPlant,
    DetectorResponse,
    LoopbackPath,
)
from .native_protocol import (
    CONTROL_RESULT_PROTOCOL,
    CONTROL_TRANSPORT_PROTOCOL,
    ControlEnvelope,
    decode_acquisition_payload,
)
from .profile import HardwareProfile, QuantizationRule
from .physical_bench import (
    RED_PITAYA_PHYSICAL_LOOPBACK_CHANNEL_MAP,
    red_pitaya_physical_loopback_envelope,
)
from .red_pitaya import (
    PHYSICAL_EVIDENCE_PROTOCOL,
    PHYSICAL_REGISTER_MAP,
    RED_PITAYA_DEFAULT_BASE_ADDRESS,
    DevMemRegisterIO,
    PhysicalExecutionEvidence,
    RedPitayaMMIOBoard,
    RegisterIO,
    sha256_file,
)
from .rtl import (
    RTL_INSTRUCTION_FORMAT_VERSION,
    RTL_INSTRUCTION_SCHEMA_VERSION,
    RTL_INSTRUCTION_WIDTH_BITS,
    RTLAcquisitionCode,
    RTLInstruction,
    RTLOpcode,
    RTLProgram,
)
from .program import (
    CONTROL_SCHEMA_VERSION,
    ChannelRole,
    ControlChannel,
    ControlEvent,
    ControlProgram,
    EventKind,
)
from .sweep import ControlSweep, SweepTargetKind
from .timing import (
    COMPILED_CONTROL_SCHEMA_VERSION,
    CONTROL_COMPILER_ID,
    CompiledControlEvent,
    CompiledControlProgram,
    CompiledControlSweep,
    QuantizedTime,
    ResourceUsage,
    compile_control_program,
    quantize_time_ns,
)
from .trace import (
    EXECUTION_TRACE_SCHEMA_VERSION,
    ExecutionTrace,
    TraceEvent,
    TraceEventKind,
)
from .virtual_controller import (
    AcquisitionProvider,
    VirtualControllerState,
    VirtualExecutionResult,
    VirtualPhotonicController,
    ZeroAcquisitionProvider,
)

__all__ = [
    "CONTROL_SCHEMA_VERSION",
    "COMPILED_CONTROL_SCHEMA_VERSION",
    "CONTROL_COMPILER_ID",
    "EXECUTION_TRACE_SCHEMA_VERSION",
    "ANALYTIC_LOOPBACK_MODEL_ID",
    "ANALYTIC_LOOPBACK_SCHEMA_VERSION",
    "CONTROL_RESULT_PROTOCOL",
    "CONTROL_TRANSPORT_PROTOCOL",
    "BOARD_CAPABILITIES_PROTOCOL",
    "BOARD_PROGRAM_PROTOCOL",
    "BOARD_REGISTER_MAP",
    "BOARD_RESULT_PROTOCOL",
    "PHYSICAL_EVIDENCE_PROTOCOL",
    "PHYSICAL_REGISTER_MAP",
    "RED_PITAYA_DEFAULT_BASE_ADDRESS",
    "RED_PITAYA_PHYSICAL_LOOPBACK_CHANNEL_MAP",
    "AcquisitionKind",
    "AcquisitionRecord",
    "AnalyticLoopbackConfig",
    "AnalyticLoopbackPlant",
    "BoardCapabilities",
    "BoardExecutionResult",
    "BoardProgramImage",
    "DevMemRegisterIO",
    "ChannelRole",
    "CompiledControlEvent",
    "CompiledControlProgram",
    "CompiledControlSweep",
    "ControlChannel",
    "ControlEnvelope",
    "ControlEvent",
    "ControlProgram",
    "ControlSweep",
    "EventKind",
    "ExecutionTrace",
    "DetectorResponse",
    "HardwareProfile",
    "QuantizationRule",
    "RTL_INSTRUCTION_FORMAT_VERSION",
    "RTL_INSTRUCTION_SCHEMA_VERSION",
    "RTL_INSTRUCTION_WIDTH_BITS",
    "RTLAcquisitionCode",
    "RTLInstruction",
    "RTLOpcode",
    "RTLProgram",
    "QuantizedTime",
    "ResourceUsage",
    "LoopbackPath",
    "P6BoardBridge",
    "PhysicalExecutionEvidence",
    "RedPitayaMMIOBoard",
    "RegisterIO",
    "SweepTargetKind",
    "SoftwareBoard",
    "TraceEvent",
    "TraceEventKind",
    "AcquisitionProvider",
    "VirtualControllerState",
    "VirtualExecutionResult",
    "VirtualPhotonicController",
    "ZeroAcquisitionProvider",
    "compile_control_program",
    "decode_acquisition_payload",
    "decode_control_request_frame",
    "encode_control_request_frame",
    "encode_control_result_frame",
    "quantize_time_ns",
    "red_pitaya_physical_loopback_envelope",
    "sha256_file",
]
